import type { Blueprint, BlueprintAgent, Files } from "@/lib/schemas";
import { getFramework } from "@/lib/frameworks";
import { slugify } from "@/lib/utils";

export function toIdentifier(input: string): string {
  const id = slugify(input, 60).replace(/-/g, "_");
  if (!id) return "tool";
  return /^[0-9]/.test(id) ? `t_${id}` : id;
}

export function agentSlug(agent: Pick<BlueprintAgent, "name">): string {
  return toIdentifier(agent.name) || "agent";
}

const lit = (s: string) => JSON.stringify(s);

function pyTools(agent: BlueprintAgent, decorator = ""): string {
  if (agent.tools.length === 0) return "";
  return (
    agent.tools
      .map((t) => {
        const fn = toIdentifier(t);
        return `${decorator ? decorator + "\n" : ""}def ${fn}(query: str) -> str:\n    """${t.replace(/"/g, "'")}"""\n    # TODO: connect to your system of record\n    return f"${fn} result for: {query}"`;
      })
      .join("\n\n\n") + "\n\n\n"
  );
}

const toolList = (agent: BlueprintAgent) => agent.tools.map(toIdentifier).join(", ");

export function generateAgentCode(agent: BlueprintAgent, frameworkId: string): string {
  const fw = getFramework(frameworkId);
  const name = agent.name;
  const instr = agent.instructions;
  const slug = agentSlug(agent);

  switch (fw.id) {
    case "langgraph":
      return `"""${name} — generated by Architect (LangGraph)"""
from langchain_anthropic import ChatAnthropic
from langgraph.prebuilt import create_react_agent


${pyTools(agent)}model = ChatAnthropic(model="claude-opus-5")

${slug} = create_react_agent(
    model,
    tools=[${toolList(agent)}],
    prompt=${lit(instr)},
)

if __name__ == "__main__":
    result = ${slug}.invoke({"messages": [("user", ${lit(`Trigger: ${agent.trigger}`)})]})
    print(result["messages"][-1].content)
`;
    case "crewai":
      return `"""${name} — generated by Architect (CrewAI)"""
from crewai import Agent, Crew, Task
from crewai.tools import tool


${pyTools(agent, "@tool")}${slug} = Agent(
    role=${lit(name)},
    goal=${lit(agent.role)},
    backstory=${lit(instr)},
    tools=[${toolList(agent)}],
    llm="anthropic/claude-opus-5",
)

task = Task(
    description=${lit(`Handle: ${agent.trigger}`)},
    expected_output="A concise, actionable result",
    agent=${slug},
)

if __name__ == "__main__":
    print(Crew(agents=[${slug}], tasks=[task]).kickoff())
`;
    case "openai-agents":
      return `"""${name} — generated by Architect (OpenAI Agents SDK)"""
from agents import Agent, Runner, function_tool


${pyTools(agent, "@function_tool")}${slug} = Agent(
    name=${lit(name)},
    instructions=${lit(instr)},
    tools=[${toolList(agent)}],
)

if __name__ == "__main__":
    result = Runner.run_sync(${slug}, ${lit(`Trigger: ${agent.trigger}`)})
    print(result.final_output)
`;
    case "claude-agent-sdk":
      return `// ${name} — generated by Architect (Claude Agent SDK)
import { query } from "@anthropic-ai/claude-agent-sdk";

const systemPrompt = ${lit(instr)};

export async function run${slug
        .split("_")
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join("")}(input: string) {
  for await (const message of query({
    prompt: input,
    options: {
      systemPrompt,
      allowedTools: ${JSON.stringify(agent.tools.map(toIdentifier))},
    },
  })) {
    if (message.type === "result") return message;
  }
}
`;
    case "autogen":
      return `"""${name} — generated by Architect (AutoGen)"""
import asyncio

from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.anthropic import AnthropicChatCompletionClient


${pyTools(agent)}${slug} = AssistantAgent(
    name=${lit(slug)},
    model_client=AnthropicChatCompletionClient(model="claude-opus-5"),
    system_message=${lit(instr)},
    tools=[${toolList(agent)}],
)

if __name__ == "__main__":
    asyncio.run(${slug}.run(task=${lit(`Trigger: ${agent.trigger}`)}))
`;
    case "lyzr":
    default:
      return `"""${name} — generated by Architect (Lyzr ADK)"""
from lyzr import Studio

studio = Studio(api_key="$LYZR_API_KEY")

${slug} = studio.create_agent(
    name=${lit(name)},
    provider="anthropic",
    model="claude-opus-5",
    role=${lit(agent.role)},
    goal=${lit(`Respond to: ${agent.trigger}`)},
    instructions=${lit(instr)},
    memory=True,
    tools=${JSON.stringify(agent.tools.map(toIdentifier))},
    responsible_ai={"pii_redaction": True, "toxicity_filter": True},
)

if __name__ == "__main__":
    print(${slug}.run(${lit(`Trigger: ${agent.trigger}`)}).response)
`;
  }
}

export function generateAgentFiles(blueprint: Blueprint, frameworkId: string): Files {
  const fw = getFramework(frameworkId);
  const files: Files = {};
  for (const agent of blueprint.agents) {
    files[fw.file(agentSlug(agent))] = generateAgentCode(agent, fw.id);
  }
  files["architect.json"] = JSON.stringify(
    {
      app: blueprint.appName,
      framework: fw.id,
      agents: blueprint.agents.map((a) => ({
        name: a.name,
        file: fw.file(agentSlug(a)),
        trigger: a.trigger,
        tools: a.tools,
      })),
      integrations: blueprint.integrations,
    },
    null,
    2,
  );
  return files;
}

export function generateReadme(blueprint: Blueprint, frameworkId: string): string {
  const fw = getFramework(frameworkId);
  const pages = blueprint.pages.map((p) => `- **${p.name}** — ${p.purpose}`).join("\n");
  const agents = blueprint.agents
    .map((a) => `- **${a.name}** (${a.trigger}) — ${a.role}`)
    .join("\n");
  const entities = blueprint.dataModel
    .map((e) => `- \`${e.entity}\`: ${e.fields.map((f) => `${f.name}:${f.type}`).join(", ")}`)
    .join("\n");
  return `# ${blueprint.appName}

> ${blueprint.tagline}

${blueprint.summary}

Built with [Architect](https://architect.new) · agents in **${fw.name}**.

## Pages
${pages}

## Agents
${agents || "_none_"}

## Data model
${entities}

## Run locally
\`\`\`bash
# UI
npx serve .
# Agents (${fw.language})
${fw.language === "python" ? "pip install -r requirements.txt\npython " + fw.file(agentSlug(blueprint.agents[0] ?? { name: "agent" })) : "npm install\nnpx tsx " + fw.file(agentSlug(blueprint.agents[0] ?? { name: "agent" }))}
\`\`\`
`;
}
